blank_issues_enabled: true
contact_links:
  - name: Ask a question/open a discussion
    url: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions
    about: To ask a question or open a discussion please use a dedicated section.
  - name: Report a bug in map camera (Xiaomi Cloud Map Extractor)
    url: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues
    about: This is the issue tracker for the Lovelace card. Please report issues with the camera in its repository.
